version: "3.7"

services:
  passengers:
    build:
      context: passenger_service
    depends_on:
      - rabbit

  drivers:
    build:
      context: driver_service
    depends_on:
      - rabbit

  trip:
    build:
      context: trip_service
    depends_on:
      - rabbit

  gateway:
    build:
      context: gateway
    depends_on:
      - rabbit
    ports:
      - "8003:8000"

  redis:
    image: redis:alpine
    hostname: redis
    volumes:
      - redis-trip-volume:/data

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
volumes:
  redis-trip-volume:
